codecov:
  token: c429221f-dce8-4279-b113-d867fee6755a 
  url: "http"  
  slug: "wxh07151732@163.com/WenxiaohuaEdward "  
  branch: dev  
  bot: WenxiaohuaEdward  

  notify: 
    after_n_builds: 120    
    require_ci_to_pass: yes                
    countdown: 120          
    delay: 120              
coverage:
  precision: 2  # 2 = xx.xx%, 0 = xx%
  round: down|up|nearest # default down
  range: 50...60 # default 70...90. red...green

  notify:
    irc:
      default:
        server: "chat.freenode.net"|encrypted
        branches: null  # all branches by default
        threshold: 1%
        message: "Coverage {{changed}} for {{wxh07151732@163.com}}/{{WenxiaohuaEdward }}" 
        flags: null
        paths: null

    slack:
      default:
        url: "http"|encrypted
        threshold: 1%
        branches: null  # all branches by default
        message: "Coverage {{changed}} for {{wxh07151732@163.com}}/{{WenxiaohuaEdward }}"  
        attachments: "sunburst, diff"
        only_pulls: false
        flags: null
        paths: null

    email:
      default:
        to:
          - wxh07151732@163.com
          - &author
        threshold: 1%
        only_pulls: false
        layout: header, diff, trends
        flags: null
        paths: null

    hipchat:
      default:
        url: "http"|encrypted
        room: name|id
        threshold: 1%
        token: encrypted
        branches: null  # all branches by default
        notify: false  # if the hipchat message is silent or loud (default false)
        message: "Coverage {{changed}} for {{wxh07151732@163.com}}/{{WenxiaohuaEdward}}"  
        flags: null
        paths: null

    gitter:
      url: "http"|encrypted
      threshold: 1%
      branches: null  # all branches by default
      message: "Coverage {{changed}} for {{wxh07151732@163.com}}/{{WenxiaohuaEdward}}"  

    webhooks:
      _name_:
        url: "http"|encrypted
        threshold: 1%
        branches: null  # all branches by default

  status:
    project:
      default:
        against: parent
        target: auto
        threshold: 1%
        branches:
          - master
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder

    patch:
      default:
        against: parent
        target: 80%
        branches: null
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder
    
    changes:
      default:
        against: parent
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags:
          - integration
        paths:
          - folder

  flags:
    integration:
      branches:
        - master
      ignore:
        - app/ui

  ignore: 
    - tests/*
  
  fixes:
    - "old_path::new_path"

comment:
  layout: header, diff, trends, uncovered
  branches: *
  behavior: default 
