package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SERIES_GUIDE_SEASON".
 */
public class SeriesGuideSeason {

    private Long id;
    private String title;
    private Double score;
    private String cat;
    private String brief;
    private String cover;
    private String enTitle;
    private String playStatus;
    private String createTimeStr;
    private Boolean isFocus;
    private Integer viewCount;
    private Integer updateInfo;
    private Integer total;
    private Long createTime;
    private Long updateTime;

    public SeriesGuideSeason() {
    }

    public SeriesGuideSeason(Long id) {
        this.id = id;
    }

    public SeriesGuideSeason(Long id, String title, Double score, String cat, String brief, String cover, String enTitle, String playStatus, String createTimeStr, Boolean isFocus, Integer viewCount, Integer updateInfo, Integer total, Long createTime, Long updateTime) {
        this.id = id;
        this.title = title;
        this.score = score;
        this.cat = cat;
        this.brief = brief;
        this.cover = cover;
        this.enTitle = enTitle;
        this.playStatus = playStatus;
        this.createTimeStr = createTimeStr;
        this.isFocus = isFocus;
        this.viewCount = viewCount;
        this.updateInfo = updateInfo;
        this.total = total;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Double getScore() {
        return score;
    }

    public void setScore(Double score) {
        this.score = score;
    }

    public String getCat() {
        return cat;
    }

    public void setCat(String cat) {
        this.cat = cat;
    }

    public String getBrief() {
        return brief;
    }

    public void setBrief(String brief) {
        this.brief = brief;
    }

    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }

    public String getEnTitle() {
        return enTitle;
    }

    public void setEnTitle(String enTitle) {
        this.enTitle = enTitle;
    }

    public String getPlayStatus() {
        return playStatus;
    }

    public void setPlayStatus(String playStatus) {
        this.playStatus = playStatus;
    }

    public String getCreateTimeStr() {
        return createTimeStr;
    }

    public void setCreateTimeStr(String createTimeStr) {
        this.createTimeStr = createTimeStr;
    }

    public Boolean getIsFocus() {
        return isFocus;
    }

    public void setIsFocus(Boolean isFocus) {
        this.isFocus = isFocus;
    }

    public Integer getViewCount() {
        return viewCount;
    }

    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    public Integer getUpdateInfo() {
        return updateInfo;
    }

    public void setUpdateInfo(Integer updateInfo) {
        this.updateInfo = updateInfo;
    }

    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

}
